version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_NAME=Matchify
      - DB_USER=test
      - DB_PASS=test
      - DB_HOST=db
      - REDIS_HOST=redis        # Host de Redis
      - REDIS_PORT=6379         # Puerto de Redis
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules  # Evita conflictos con node_modules en el host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0  # Asegura que el servidor escuche en todas las interfaces
      - PORT=3000       # Define el puerto de la aplicación
    stdin_open: true  # Permite interacciones si es necesario
    tty: true         # Mantiene el contenedor en ejecución

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: Matchify
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"             # Puerto donde escucha Redis

volumes:
  mysql-data:
