version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_NAME=Matchify
      - DB_USER=test
      - DB_PASS=test
      - DB_HOST=db
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: Matchify
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
