version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_NAME=Matchify
      - DB_USER=test
      - DB_PASS=test
      - DB_HOST=db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Evita conflictos con host y contenedor
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules # Evita conflictos con host y contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: Matchify
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
